const fs = require('fs');
const content = fs.readFileSync('backend/controllers/auth.controller.js', 'utf8');
const lines = content.split('\n');
const newLines = lines.slice(0, 329); // Up to WHERE id_usuario = ${user.id_usuario}

newLines.push('    `;');
newLines.push('');
newLines.push('    return res.status(200).json({ message: "Contraseña actualizada exitosamente" });');
newLines.push('  } catch (error) {');
newLines.push('    console.error("💥 ERROR en resetPassword:", error);');
newLines.push('    return res.status(500).json({ message: "Error en el servidor" });');
newLines.push('  }');
newLines.push('};');
newLines.push('');
newLines.push('export const verifyEmail = async (req, res) => {');
newLines.push('  try {');
newLines.push('    const { email, code } = req.body;');
newLines.push('    if (!email || !code) return res.status(400).json({ message: "Email y código son requeridos" });');
newLines.push('    const [user] = await sql`SELECT * FROM usuarios WHERE email = ${email}`;');
newLines.push('    if (!user) return res.status(404).json({ message: "Usuario no encontrado" });');
newLines.push('    const [verificacion] = await sql`SELECT * FROM usuario_verificaciones WHERE id_usuario = ${user.id_usuario}`;');
newLines.push('    if (!verificacion) return res.status(400).json({ message: "No se encontró proceso de verificación" });');
newLines.push('    if (verificacion.email_verificado) return res.status(400).json({ message: "El correo ya está verificado" });');
newLines.push('    if (verificacion.codigo_verificacion !== code) return res.status(400).json({ message: "Código de verificación incorrecto" });');
newLines.push('    await sql`UPDATE usuario_verificaciones SET email_verificado = true, codigo_verificacion = NULL WHERE id_usuario = ${user.id_usuario}`;');
newLines.push('    let permisos = [];');
newLines.push('    if (user.id_rol === 1) {');
newLines.push('      const todos = await sql`SELECT nombre FROM permisos WHERE estado = true`;');
newLines.push('      permisos = todos.map(p => p.nombre);');
newLines.push('    } else {');
newLines.push('      const userPerms = await sql`SELECT p.nombre FROM roles_permisos rp JOIN permisos p ON rp.id_permiso = p.id_permiso WHERE rp.id_rol = ${user.id_rol} AND p.estado = true`;');
newLines.push('      permisos = userPerms.map(p => p.nombre);');
newLines.push('    }');
newLines.push('    const token = jwt.sign({ id_usuario: user.id_usuario, email: user.email, rol: user.id_rol, permisos }, process.env.JWT_SECRET, { expiresIn: "24h" });');
newLines.push('    emailService.enviarBienvenida(user.email, user.nombre).catch(e => console.error("💥 Error email bienvenida:", e));');
newLines.push('    return res.json({ message: "Correo verificado exitosamente", token, usuario: { id_usuario: user.id_usuario, nombre: user.nombre, apellido: user.apellido, email: user.email, id_rol: user.id_rol, estado: user.estado, permisos } });');
newLines.push('  } catch (error) {');
newLines.push('    console.error("💥 ERROR en verifyEmail:", error);');
newLines.push('    return res.status(500).json({ message: "Error en el servidor" });');
newLines.push('  }');
newLines.push('};');

fs.writeFileSync('backend/controllers/auth.controller.js', newLines.join('\n'));
console.log('File rewritten cleanly');
